#! /bin/sh

### BEGIN INIT INFO
# Provides:          vxland
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start VXLAN Tunnel End-Point
# Description:       This script starts or stops VXLAN Tunnel End-Point
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="VXLAN Tunnel End-Point"
NAME=vxland
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/var/run/$NAME.pid

. /lib/init/vars.sh

. /lib/lsb/init-functions

if [ -f /etc/default/$NAME ]; then
    . /etc/default/$NAME
fi

if [ -n "$VXLAND_DIR" ]; then
    DAEMON=$VXLAND_DIR/$NAME
else
    DAEMON=/usr/sbin/$NAME
fi

[ -x "$DAEMON" ] || exit 0

if [ -n "$VXLAND_OPTS" ]; then
    DAEMON_ARGS=$VXLAND_OPTS
else
    DAEMON_ARGS="-s -d -i eth0"
fi

do_start()
{
    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
	--test > /dev/null || return 1
    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
	-- $DAEMON_ARGS || return 2
}

do_stop()
{
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
    RETVAL="$?"
    rm -f $PIDFILE
    return "$RETVAL"
}

case "$1" in
    start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
    stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
    status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
    restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	    0|1)
		do_start
		case "$?" in
		    0) log_end_msg 0 ;;
		    1) log_end_msg 1 ;;
		    *) log_end_msg 1 ;;
		esac
		;;
	    *)
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
