#!/bin/sh

case "$IFACE" in
  *:*)
    exit 0
  ;;
  *.*)
    exit 0
  ;;
  dummy*)
    ip link add $IFACE type dummy
  ;;
  *)
    exit 0
  ;;
esac

if [ -n "$IF_HW_MAC_ADDRESS" ]; then
    ip link set $IFACE address $IF_HW_MAC_ADDRESS
fi
