include_recipe 'virtual-network-platform::getting-the-source-code'
include_recipe 'virtual-network-platform::backend-database'
include_recipe 'virtual-network-platform::ruby193-and-bundler'
include_recipe 'virtual-network-platform::virtual-network-manager'
include_recipe 'virtual-network-platform::configuration-frontend'
