#!/usr/bin/env ruby
#
# Copyright (C) 2013 NEC Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

required_path = File.expand_path( "../lib", __FILE__ )
$LOAD_PATH.unshift required_path unless $LOAD_PATH.include? required_path

require 'yaml'

config = ( YAML.load_file( File.dirname( __FILE__ ) + '/configure.yml' ) or {} )

if config[ 'agent' ] == 'reflector_agent'
  require 'reflector_agent'
  ReflectorAgent.run!
else
  require 'tunnel_endpoint_agent'
  TunnelEndpointAgent.run!
end
