#! /bin/sh

### BEGIN INIT INFO
# Provides:          virtual_network_manager
# Required-Start:    $remote_fs $network $syslog mysql trema
# Required-Stop:     $remote_fs $network $syslog mysql trema
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Virtual Network Manager
# Description:       This script starts or stops Virtual Network Manager.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Virtual Network Manager"
NAME=virtual_network_manager
SCRIPTNAME=/etc/init.d/$NAME

. /lib/init/vars.sh

. /lib/lsb/init-functions

if [ -f /etc/default/trema ]; then
    . /etc/default/trema  # Read TREMA_HOME from this
fi

PIDDIR=$TREMA_HOME/tmp/pid
PIDFILE=$PIDDIR/$NAME.pid

if [ -f /etc/default/$NAME ]; then
    . /etc/default/$NAME
fi

if [ -n "$VIRTUAL_NETWORK_MANAGER_DIR" ]; then
    DAEMON=$VIRTUAL_NETWORK_MANAGER_DIR/$NAME
else
    DAEMON=/usr/sbin/$NAME
fi

DAEMON_ARGS="-b $DB_HOST -p $DB_PORT -u $DB_USERNAME -c $DB_PASSWORD -m $DB_NAME -g -d"

[ -x "$DAEMON" ] || exit 0

do_start()
{
    TREMA_HOME=$TREMA_HOME start-stop-daemon --start --quiet --pidfile $PIDFILE \
	--exec $DAEMON --test > /dev/null || return 1
    TREMA_HOME=$TREMA_HOME start-stop-daemon --start --quiet --pidfile $PIDFILE \
	--exec $DAEMON -- $DAEMON_ARGS || return 2
}

do_stop()
{
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
    RETVAL="$?"
    return "$RETVAL"
}

case "$1" in
    start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
    stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
	    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
    status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
    restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	    0|1)
		do_start
		case "$?" in
		    0) log_end_msg 0 ;;
		    1) log_end_msg 1 ;;
		    *) log_end_msg 1 ;;
		esac
		;;
	    *)
		log_end_msg 1
		;;
	esac
	;;
    *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
