#!/bin/sh -x

./db/create-database

./slice create 123 'network-123'
# A slice is created successfully.

./slice list
# ID      Description                     State                Updated At
# 123     network-123                     confirmed            2013-01-01 13:01:01

./slice add-port -i 1 123 0xe0 1 none 'e0-1 network-123'
# A port is added successfully.

./slice add-mac 123 1 0:0:0:e0:0:1
# A MAC address is added successfully.

./slice -Dd add-port -i 2 123 0xe1 1 none 'e1-1 network-123'
# A port is added successfully.

./slice -Dd add-mac 123 2 0:0:0:e1:0:2
# A MAC address is added successfully.
